Exception: STATUS_ACCESS_VIOLATION at rip=00561BDBDD6
rax=0000000561D295E0 rbx=000006FFFEF9C730 rcx=0000000561E00F40
rdx=0000000000000000 rsi=0000000536564560 rdi=000006FFFF2715D0
r8 =000006FFFEF9CC80 r9 =6E3FBCE545E2C2B1 r10=0000000000000007
r11=0000000000000007 r12=000006FFFEE99750 r13=0000000536562C10
r14=000006FFFEE87F70 r15=0000000000000000
rbp=0000000000000002 rsp=00000000FFFF9AD0
program=C:\msys64\usr\bin\python3.exe, pid 1411, thread main
cs=0033 ds=002B es=002B fs=0053 gs=002B ss=002B
